### ISSUE TITLE
Snap position is incorrect if 'Half Resolution' is enabled in the editor viewport

### ISSUE THREAD

**Issue by nan0m** [mharitsnf/ExtraSnaps#10]
see above

**Comment by mharitsnf** [comment]
Hey! Sorry for taking a while on this. I made a PR #11 for the fix, feel free to take a look. I think it's working fine, but I'll test a bit further tomorrow and merge it afterwards.

**Comment by mharitsnf** [comment]
Merged to master, as everything seems good, and closing this one for now. I'll keep an eye and reopen the issue if there's something wrong with it. Feel free to do the same. Thanks for the report again!
