### ISSUE TITLE
Doesn't seem to work on children node3Ds

### ISSUE THREAD

**Issue by nan0m** [mharitsnf/ExtraSnaps#3]
Trying to snap the child node3D of a parent node3D, the child goes to the wrong position, somewhere around world origin.

**Comment by oparisy** [comment]
Does this work as expected if you unparent those nodes?

Also note that as discussed in issue #1, snapping will currently only work with physics objects.

**Comment by nan0m** [comment]
exactly, if I bring that node to the topmost level in the edited scene, it works perfectly.

**Comment by mharitsnf** [comment]
Hey, Thanks for bringing this up! I tried this and I think the issue was that the plugin uses local transform instead of global transform, making it weird when you want to snap children of Node3D.

I made a pull request (#4) that addresses this issue. Feel free to give it a try first :D

**Comment by nan0m** [comment]
works! @mharitsnf
