### ISSUE TITLE
snapped object moves closer and closer to the camera

### ISSUE THREAD

**Issue by nan0m** [mharitsnf/ExtraSnaps#5]
If you snap a thing that has a collider at the snapping point / origin of the object. The RayCast3D of the Plugin hits the collider each frame, thereby displacing the origin of the object to get closer to the camera. Thereby the object moves closer and closer to the camera. 

This could be avoided if the collider of the currently selected / snapped object is excluded form the RayCast3D collisions. 

Node tree to reproduce:
MeshInstance3D
--StaticBody3D
----Collisionshape3D

set a BoxShape3D on the CollisionShape3D.

Now select the MeshInstance3D and try to move it with extra_snaps. It moves closer to the camera each frame.

**Comment by mharitsnf** [comment]
Thanks! Something like this also happened on CSG objects before, but this is something new.

I made a PR #6 to address this issue. Feel free to try it first :)
